name: AltEnergy
favicon: null
layout_spectrum: 0.7036461743991822
typography_spectrum: 0.8617546330206096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3678113392088562
  lightness: 0.6323457576800138
  saturation: 0.18196146446280181
  rhythmicContrast: 0.931872647954151
purpose: []
